---

#- name: Install lvm2
#  apt:
#    name: lvm2
#    state: latest 
#    update_cache: no 

# Create volume groups
# Create cs_volumes in the groups:

- name: Create volume groups
  lvg:
    vg: "{{ item.name }}"
    pvs: "{{ item.physical_volumes }}"
    pesize: 4M
    state: present
  # all volume groups
  loop: "{{ lvm.volume_groups }}"
    
- name: Create logical volumes
  lvol:
    vg: "{{ item[0].name }}"
    lv: "{{ item[1].name }}"
    size: "{{ item[1].size }}"
    active: yes
    shrink: "{{ 'no' if item[1].size == '100%FREE' else 'yes' }}"
    state: present
  register: lvdata
  # all volumes in the volumes groups
  loop: "{{ lvm.volume_groups | subelements('volumes', skip_missing = True) }}"
