---

- import_tasks: ca-certs.yml
- import_tasks: upgrade.yml
- import_tasks: aptitude.yml
- import_tasks: python3-base.yml
- import_tasks: python3-other.yml
- import_tasks: pips.yml
- import_tasks: lvm2.yml
  