---

- name: Install setuptools
  apt:
    name: python-setuptools
    state: latest 
    update_cache: false 

- name: Install pip
  apt:
    name: python3-pip
    state: latest 
    update_cache: false 

