---

########################################
# Create data container for postgresql
# Create postgres application container

- name: create volume for postgres data
  docker_volume:
    name: "{{ db_data_volume_name }}"
    state: present
    driver: local
    #driver_options: "size=500M"
      


- name: get postgresql docker image
  docker_image: 
    name: "{{ db_docker_image }}"
    tag: "alpine"
    source: pull

- name: create postgresql docker container
  docker_container:
    name: "{{ db_docker_container_name }}"
    image: "{{ db_docker_image }}"
    state: started
    recreate: yes # make conditional
    memory: "{{ db_max_memory }}"
    mounts: 
      - data:
        source: "{{ db_data_volume_name }}"
        target: "{{ db_data_volume_mount_point }}"
        
    user: "root"
    restart_policy: always

