---

# Create mount point for postgresql data
#- name: Create mount directory for postgresql data
#  file:
#    path: "{{ db_lvm_data_volume_mount_point }}"
#    state: directory
#    group: root 
#    mode: u=rwx,g=,o=

# Create logical volume
- name: create and mount data logival volume for postgresql
  lvol:
    vg: "{{ docker.data.volume_group }}"
    lv: "{{ db_lvm_data_volume_name }}"
    size: "{{ db_lvm_data_volume_size }}"
    active: yes
    shrink: yes
    state: present
  register: lvdata    

# Format logical volume
- name: Format volume for postgresql data
  filesystem:
    fstype: xfs
    opts: -n ftype=1
    dev: "/dev/{{ docker.data.volume_group }}/{{ db_lvm_data_volume_name }}"

# Mount logical volume
- name: "Mount {{ db_lvm_data_volume_mount_point }}"
  mount:
    path: "{{ db_lvm_data_volume_mount_point }}"
    src: "/dev/{{ docker.data.volume_group }}/{{ db_lvm_data_volume_name }}"
    fstype: xfs
    opts: defaults
    state: mounted

- name: get postgresql docker image
  docker_image: 
    name: "{{ db_docker_image }}"
    source: pull

- name: create postgresql docker container
  docker_container:
    name: "{{ db_docker_container_name }}"
    image: "{{ db_docker_image }}"
    state: started
    memory: "{{ db_max_memory }}"
    restart_policy: always

