---

# Some prerequisites
- name: Add PostgreSQL GPG apt Key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ {{ansible_distribution_release}}-pgdg main

- name: Install Postgresql development lib, needed for pip module psycopg2
  apt:
    name: libpq-dev
    state: latest 
    update_cache: false     

- name: Install PostgreSQL client packages
  apt:
    name: "{{ item }}"
    state: latest 
    update_cache: false
  loop:
    - postgresql-client-common
    - postgresql-client-12

- name: Install python3-psycopg2 pip
  pip:
    name: psycopg2
    state: present

########################################
# Create volume for postgresql data
# Create postgres application container

# If the volume should be recreated, stop docker postgresql container

- name: "Stop docker container {{ db_docker_container_name }}"
  docker_container:
    name: "{{ db_docker_container_name }}"
    image: "{{ db_docker_image }}"
    state: absent  # Remove container
    keep_volumes: false
  when: recreate_postgresql_volume == "always"

# (Re)Create the volumes
- name: Create volumes for postgres
  docker_volume:
    name: "{{ item }}"
    state: present
    driver: local
    recreate: "{{ recreate_postgresql_volume }}"
  loop:
    - "{{ db_data_volume_name }}"

# Get the specified image for Postgresql
- name: get postgresql docker image
  docker_image: 
    name: "{{ db_docker_image }}"
    tag: "{{ db_docker_image_tag }}"
    source: pull

# Create / start the container. Recreate is conditional
- name: create postgresql docker container
  docker_container:
    name: "{{ db_docker_container_name }}"
    image: "{{ db_docker_image }}"
    state: started
    recreate: "{{ recreate_postgresql_container }}"
    memory: "{{ db_max_memory }}"
    mounts: 
      - source: "{{ db_data_volume_name }}"
        target: "{{ db_data_volume_container_mount_point }}"
        type: volume
    hostname: "{{ db_docker_container_hostname }}"
    exposed_ports: "{{ db_docker_container_exposes_ports }}"
    published_ports: "{{ db_docker_container_publish_ports }}"
    user: "root" # should be changed
    restart_policy: always
  register: postgresql_inspect_data

- name: Store IP of Postgresql server
  set_fact: 
    postgres_ip: "{{ postgresql_inspect_data['ansible_facts']['docker_container']['NetworkSettings']['IPAddress'] }}"

- name: "Wait for PostgreSQL @ {{ postgres_ip }} : {{ db_docker_container_exposes_ports[0] }} to respond"
  wait_for:
    host: "{{ postgres_ip }}"
    port: "{{ db_docker_container_exposes_ports[0] }}"
    state: drained
    connect_timeout: 1
    timeout: 30
  register: postgres_responding
  until: postgres_responding is success
  retries: 10

#- name: Create Postgresql user
#  block:
#  - name: "Create Postgresql {{ db_postgres_dbuser }} account"
#    postgresql_user:
#      encrypted: true
#      login_host: "{{ postgres_ip }}"
#      login_user: "postgres"
#      db: "{{ db_postgres_dbname }}"
#      name: "{{ db_postgres_dbuser }}"
#      password: "{{ db_postgres_password }}"
#
#  when: postgres_responding is success