---

- name: Check domain name
  fail:
    msg: "Please give a valid domain name"
  when: openldap_domain_input is not match(".*\..*")

# Some prerequisites
- name: Install python3-ldap
  apt:
    name: "{{ item }}"
    state: latest 
    update_cache: false 
  loop:
    - python3-ldap

########################################
# Create data volumes for OpenLDAP
# Create OpenLDAP application container

# If the volume should be recreated, stop docker openldap container

- name: "Stop docker container {{ openldap_docker_container_name }}"
  docker_container:
    name: "{{ openldap_docker_container_name }}"
    #image: "{{ openldap_docker_image }}"
    state: absent  # Remove container
    keep_volumes: false
  when: recreate_openldap_volumes == "always"

# (Re)Create the data volume
- name: Create volume for openldap data
  docker_volume:
    name: "{{ item }}"
    state: present
    driver: local
    recreate: "{{ recreate_openldap_volumes }}"
  loop: 
   - "{{ openldap_data_volume_name }}"
   - "{{ openldap_config_volume_name }}"
   - "{{ openldap_tls_volume_name }}"
    
- name: Get path to config volume for openldap container 
  docker_volume_info:
    name: "{{ openldap_config_volume_name }}"
  register: config_volume_data

- name: Get path to TLS volume for openldap container 
  docker_volume_info:
    name: "{{ openldap_tls_volume_name }}"
  register: tls_volume_data

- set_fact:
    # path to custom configuration directory on host
    custom_config_path_host: "{{ config_volume_data.volume.Mountpoint }}/custom-config"
    # path to TLS configuration directory on host
    custom_tls_path_host: "{{ tls_volume_data.volume.Mountpoint }}"
    # path to custom configuration directory in container
    custom_config_path_container: "{{ openldap_config_volume_container_mount_point }}/custom-config"
    # domain components
    install_domain_dc: "dc={{ openldap_domain_input.split('.') | join(',dc=') }}"

- name: Copy private key, custom certificates and dhparam.pem to custom config directory on host
  copy:
    dest: "{{ custom_tls_path_host }}"
    src: "{{ item }}"
    force: yes
    mode: u=r,g=,o=
  become: true
  become_user: root
  loop:
    - "{{ cacerts_dir }}/{{ internal_cacerts_ca_file }}"
    - "{{ certs_dir }}/{{ internal_certs_cert_file }}"
    - "{{ internal_cert_priv_key_file }}"
    - "{{ dhparams_dir }}/{{ dhparam_file }}"


##############################################
# Docker image and container creation / start 
##############################################
# Get the specified image for OpenLDAP
- name: get openldap docker image
  docker_image: 
    name: "{{ openldap_docker_image }}"
    tag: "{{ openldap_docker_image_tag }}"
    source: pull

# Create bridge network
- import_tasks: ../../common/tasks/create-bridge-network.yml

# Create / start the container. Recreate is conditional
- name: create openldap docker container
  docker_container:
    name: "{{ openldap_docker_container_name }}"
    image: "{{ openldap_docker_image }}"
    state: started
    recreate: "{{ recreate_openldap_container }}"
    memory: "{{ openldap_max_memory }}"
    privileged: false
    user: root
    env:
      LDAP_ORGANISATION: "{{ openldap_organization_name_input }}"
      LDAP_DOMAIN: "{{ openldap_domain_input }}"
      LDAP_BASE_DN: "{{ openldap_domain_input }}"
      LDAP_BACKEND: "{{ openldap_backend_db }}"
      LDAP_TLS: "true"
      LDAP_TLS_CA_CRT_FILENAME: "{{ internal_cacerts_ca_file }}"
      LDAP_TLS_CRT_FILENAME: "{{ internal_certs_cert_file }}"
      LDAP_TLS_KEY_FILENAME: "{{ internal_cert_priv_key_file | basename }}"
      LDAP_TLS_DH_PARAM_FILENAME: "{{ dhparam_file }}"
      LDAP_TLS_CIPHER_SUITE: "SECURE256:+SECURE128:-VERS-TLS-ALL:+VERS-TLS1.2:-RSA:-DHE-DSS:-CAMELLIA-128-CBC:-CAMELLIA-256-CBC"
      LDAP_TLS_ENFORCE: "false"
      LDAP_TLS_VERIFY_CLIENT: "try"
    mounts: 
      - source: "{{ openldap_data_volume_name }}"
        target: "{{ openldap_data_volume_container_mount_point }}"
        type: volume
      - source: "{{ openldap_config_volume_name }}"
        target: "{{ openldap_config_volume_container_mount_point }}"
        type: volume
      - source: "{{ openldap_tls_volume_name }}"
        target: "{{ openldap_tls_volume_container_mount_point }}"
        type: volume
    hostname: "{{ openldap_docker_container_hostname }}"
    network_mode: bridge
    networks:
      - name: "InternalNet"
        aliases: "{{ openldap_docker_container_hostname }}"
    networks_cli_compatible: yes
    exposed_ports: "{{ openldap_docker_container_exposes_ports }}"
    published_ports: "{{ openldap_docker_container_publish_ports }}"
    restart_policy: always
  register: openldap_inspect_data

- set_fact:
    # ip of openldap container
    openldap_ip: "{{ openldap_inspect_data['ansible_facts']['docker_container']['NetworkSettings']['IPAddress'] }}"

- name: Wait for OpenLDAP container to be fully started
  docker_container_info:
    name: "{{ openldap_docker_container_name }}"
  register: result
  until: result.container.State.Status == 'running'
  retries: 10

- name: "Wait for OpenLDAP ldapi:// to be listening"
  shell: "docker exec openldap ldapsearch -H ldapi:// -LLL -Q -Y EXTERNAL -b cn=admin,{{ install_domain_dc }}"
  become: true
  become_user: root
  register: ldapi_responding
  until: ldapi_responding is success
  retries: 10

##################################
# Configuration
##################################

- name: "Create directory for custom config ldif filesystem ({{ custom_config_path_host }})"
  file:
    state: directory
    path: "{{ custom_config_path_host }}"

- name: change owner of cutom-config directory, private key, certificate and dhparams to openldap
  shell: "docker container exec {{ openldap_docker_container_name }} chown openldap:openldap {{ item }}"
  loop:
    - "{{ custom_config_path_container }}"
    - "{{ openldap_tls_volume_container_mount_point }}/{{ internal_cacerts_ca_file }}"
    - "{{ openldap_tls_volume_container_mount_point }}/{{ internal_certs_cert_file }}"
    - "{{ openldap_tls_volume_container_mount_point }}/{{ internal_cert_priv_key_file | basename }}"
    - "{{ openldap_tls_volume_container_mount_point }}/{{ dhparam_file }}"
    

# Create hash of the admin password.
- name: Generate password for administrator user
  shell: 
    cmd: "docker exec openldap slappasswd -s '{{ openldap_admin_password }}'"
  register: openldap_admin_password_hashed

- name: search for rootDN dn and configDIT dn
  shell: |
      docker exec --interactive {{ openldap_docker_container_name }} ldapsearch -H ldapi:// -LLL -Q -Y EXTERNAL -b "cn=config" "(olcRootDN=*)" dn olcRootDN olcRootPW
  become: true
  become_user: root
  register: result

- set_fact:
    rootDN_dn: "{{ result.stdout_lines | select('match','^dn: .*(mdb,).*') | first }}"
    configDIT_dn: "{{ result.stdout_lines | select('match','^dn: .*(config,).*') | first }}"
    admin_dn: "cn=admin,{{ install_domain_dc }}" 
    openldap_admin_password_hashed: "{{ openldap_admin_password_hashed.stdout }}"

# Change default settings. Keep the empty lines between the ldiff input blocks!
- name: Change RootDN admin password, olcSuffix and olcRootDN
  shell: |
      docker exec --interactive {{ openldap_docker_container_name }} ldapmodify -H ldapi:// -Y EXTERNAL <<EOF
      {{ rootDN_dn }}
      changetype: modify
      replace: olcRootPW
      olcRootPW: {{ openldap_admin_password_hashed }}
      EOF
  become: true
  become_user: root

- name: Change Config DIT admin password
  shell: |
      docker exec --interactive {{ openldap_docker_container_name }} ldapmodify -H ldapi:// -Y EXTERNAL <<EOF
      {{ configDIT_dn }}
      changetype: modify
      replace: olcRootPW
      olcRootPW: {{ openldap_admin_password_hashed }}
      EOF
  become: true
  become_user: root

# Change default settings. Keep the empty lines between the ldiff input blocks!
- name: Change Normal DIT admin password
  shell: |
      docker exec --interactive {{ openldap_docker_container_name }} ldapmodify -H ldaps://localhost -x -D {{ admin_dn }} -w {{ openldap_admin_password }} <<EOF
      dn: {{ admin_dn }}
      changetype: modify
      replace: userPassword
      userPassword: {{ openldap_admin_password_hashed }}
      EOF
  become: true
  become_user: root

- name: "Restart docker container {{ openldap_docker_container_name }}"
  docker_container:
    name: "{{ openldap_docker_container_name }}"
    state: started
    restart: true
