---


- name: Set up an administrator user (1)
  ldap_attr:
    server_uri: ldap://localhost/
    bind_dn: "{{ openldap_initial_dc_string }}"
    bind_pw: redhat
    dn: "olcDatabase={1}mdb,cn=config"
    name: "{{ item.key }}"
    values: "{{ item.value }}"
    state: exact
  with_dict:
    olcRootPW: "{SSHA}6zHtA20qkTmdLrJSfxo+VV3QLGS7m0CZ"

- name: Set up an administrator user (2)
  ldap_attr:
    server_uri: ldap://localhost/
    bind_dn: "{{ openldap_initial_dc_string }}"
    bind_pw: "admin"
    dn: "olcDatabase={1}mdb,cn=config"
    name: "{{ item.key }}"
    values: "{{ item.value }}"
    state: exact
  with_dict:
    olcRootDN: "cn=admin, {{ openldap_dc_string }}"
    olcRootPW: "{SSHA}6zHtA20qkTmdLrJSfxo+VV3QLGS7m0CZ"
    olcSuffix: "{{ openldap_dc_string }}"

