---

- name: Create ansible user on target system.

  # sudo to root to create user
  become: yes
  become_user: root

  vars:
    ansible_become_pass: "{{ ssh_pass }}"

  user: 
    name: "{{ deployment_user }}"
    comment: Ansible user
    groups: "{{ deployment_user_groups }}"
    generate_ssh_key: yes
    force: no
    append: no
    create_home: yes
    update_password: always
    password: "{{ deployment_user_pass | password_hash('sha512') }}"

  register: create_user_result
