---

- name: Disable ssh password login for ansible user

  vars:
    # sudo to ansible user to copy public key into authorized_keys
    ansible_become: yes
    ansible_become_user: root
    ansible_become_pass: "{{ ssh_pass }}"    

  blockinfile:
    path: /etc/ssh/sshd_config
    block: |
      Match User ansible
        PasswordAuthentication no  
    state: present
  when: copy_pub_key_result is succeeded
  notify: Restart sshd