---

- name: Check presence of files secrets-vault
  stat:
    path: "{{ secrets_vault_location }}"
  register: secrets_vault_stat

- name: File exists?
  debug: 
    msg: "{{ secrets_vault_location }} already exists, this one will be used."
  when: secrets_vault_stat.stat.exists == true

- name: "Create {{ secrets_vault_location | basename }} with secrets"
  template:
    src: templates/secrets-vault-template.yml
    dest: "{{ secrets_vault_location }}"
    owner: "{{ current_user }}"
    mode: u=rw,g=,o=
  when: secrets_vault_stat.stat.exists == false or
        recreate_vaults_input == 'y'

- name: "Encrypt {{ secrets_vault_location | basename }} containing the keypairs for the ansible user"
  shell: ansible-vault encrypt --vault-id "{{ secrets_vault_id }}@prompt" "{{ secrets_vault_location }}"
  when: secrets_vault_stat.stat.exists == false or
        recreate_vaults_input == 'y'


  
