---

########################################################################
# Create / update secrets vault: this can be done in severl playbooks,
# so the ansible_become is set to false, and delegate_to to localhost.
########################################################################

- name: Check presence of files secrets-vault
  stat:
    path: "{{ secrets_vault_location }}"
  delegate_to: localhost
  register: secrets_vault_stat
  vars:
    ansible_become: false

- name: File exists?
  debug: 
    msg: "{{ secrets_vault_location }} already exists, this one will be used."
  delegate_to: localhost
  when: secrets_vault_stat.stat.exists == true
  vars:
    ansible_become: false

- name: "Create {{ secrets_vault_location | basename }} with secrets"
  template:
    src: templates/secrets-vault-template.yml
    dest: "{{ secrets_vault_location }}"
    owner: "{{ current_user }}"
    mode: u=rw,g=,o=
  delegate_to: localhost
  when: secrets_vault_stat.stat.exists == false or
        recreate_vaults_input == 'y'
  vars:
    ansible_become: false

- name: "Encrypt {{ secrets_vault_location | basename }} containing passwords"
  shell: ansible-vault encrypt --vault-id "{{ secrets_vault_id }}@prompt" "{{ secrets_vault_location }}"
  delegate_to: localhost
  when: secrets_vault_stat.stat.exists == false or
        recreate_vaults_input == 'y'
  vars:
    ansible_become: false


  
