---

- name: Create vault yaml with secrets
  template:
    src: templates/secrets-vault-template.yml
    dest: "{{ secrets_vault_location }}"
    owner: "{{ current_user }}"
    mode: u=rw,g=,o=

- name: Encrypt vault.yml containing the keypairs for the ansible user
  shell: ansible-vault encrypt "{{ secrets_vault_location }}" --vault-id "{{ secrets_vault_id }}@prompt"
  

  
