---

# current inventory 
current_inventory_env: "{{ inventory_dir | basename }}"

# resource directory
resource_dir: "{{ inventory_dir }}/../../resources/{{ current_inventory_env }}"

# Current user is used for initial ssh connection.
current_user: "{{ lookup('env','USER') }}"
current_user_home: "{{ lookup('env','HOME') }}"

# User on the target that will be used for ansible deployments.
deployment_user: ansible
# Groups of the deployment user.
deployment_user_groups: sudo

# Current user is used for initial ssh connection.
ssh_user: "{{ current_user }}"

# keypair settings (key will only be here during setup of authentication for host)
keypair_location: "{{ current_user_home }}/ansible/keypairs/{{ current_inventory_env }}"

# private key location for key authentication ()
ssh_key_file_from_vault: "{{ keypair_location }}/ssh-key-from-vault"

