---

# LVM related vars, per host
lvm:
  volume_groups: 
  # ubuntu os
  - name: ubuntu-vg
    physical_volumes: ["/dev/sda3"]
    size: 10G
    volumes:
    - name: ubuntu-lv
      size: 9G
  # docker storage
  - name: docker-vg
    physical_volumes: ["/dev/sdb"]
    size: 2G
    volumes:
    - name: docker-storage-lv
      size: 100%FREE
  # docker persistent data
  - name: docker-data-vg
    physical_volumes: ["/dev/sdc"]
    size: 2G
    volumes:
    - name: docker-datavolumes-lv
      size: 100%FREE

# docker settings
docker:
  # docker conf settings file
  docker_conf: /etc/systemd/system/docker.service.d/http-proxy.conf
  docker_dir: /var/lib/docker
  # storage LVM
  storage:
    # for images, containers etc
    volume_group: "{{ lvm.volume_groups[1].name }}"
    logical_volume: "{{ lvm.volume_groups[1].volumes[0].name }}"
    mount_dir:  /var/lib/docker
  # data LVM
  data:
    volume_group: "{{ lvm.volume_groups[2].name }}"
    logical_volume: "{{ lvm.volume_groups[2].volumes[0].name }}"
    mount_dir:  /var/lib/docker/volumes
