---

all:
  children:
    local:
      hosts: 
        127.0.0.1:
    webservers:
      hosts:
        10.0.0.100:
    dbservers:
      hosts:
        10.0.0.100:
    all_servers:
      children:
        webservers:
        dbservers:
