---

all:
  children:
    local:
      children:
        localmachine:
          hosts: 
            127.0.0.1:
    webservers:
      children:
        webserver1:
          hosts:
            192.168.111.1:
        webserver2:
          hosts:
            192.168.111.1:
