---

- name: Check presence of files ca-vault
  stat:
    path: "{{ certkeys_vault_location }}"
  register: certkeys_vault_stat

- name: File exists?
  debug: 
    msg: "{{ certkeys_vault_location }} already exists, this one will be used."
  when: certkeys_vault_stat.stat.exists == true

- name: "Create {{ certkeys_vault_location | basename }} with keys, certificates and dhparams"
  template:
    src: templates/certs-keys-vault-template.j2
    dest: "{{ certkeys_vault_location }}"
    owner: "{{ current_user }}"
    mode: u=rw,g=,o=
  when: certkeys_vault_stat.stat.exists == false or
        recreate_vaults_input == 'y'

- name: "Encrypt {{ certkeys_vault_location | basename }} containing the keypairs, certificates and dhparams"
  shell: ansible-vault encrypt "{{ certkeys_vault_location }}" --vault-id "{{ certkeys_vault_id }}@prompt"
  when: certkeys_vault_stat.stat.exists == false or
        recreate_vaults_input == 'y'

  
