---

- name: Create directory for ca stuff
  file:
    path: "{{ ca_stuff_location }}"
    state: directory
    mode: u=rwx,g=,o=

- import_tasks: ../../common/tasks/create-sslkeypair.yml
  vars:
    priv_key_file: "{{ internal_ca_priv_key_file }}"
    pub_key_file: "{{ internal_ca_pub_key_file }}"

- import_tasks: ../../common/tasks/create-cert-request.yml
  vars:
    priv_key_file: "{{ internal_ca_priv_key_file }}"
    csr_file: "{{ internal_ca_csr }}"
    csr_config: "{{ internal_ca_config }}"

- import_tasks: ../../common/tasks/create-cert.yml
  vars:
    priv_key_file: "{{ internal_ca_priv_key_file }}"
    csr_file: "{{ internal_ca_csr }}"
    cert_file: "{{ internal_ca_cert }}"
    days: "{{ internal_ca_days }}"

- name: Store keys in variables  
  set_fact:
    vault_int_cacert_priv: "{{ lookup('file',  '{{ internal_ca_priv_key_file }}') }}"
    vault_int_cacert_pub: "{{ lookup('file',  '{{ internal_ca_pub_key_file }}') }}"
    vault_int_cacert: "{{ lookup('file',  '{{ internal_ca_cert }}') }}"


