---

- name: Create directory for certs stuff
  file:
    path: "{{ certs_stuff_location }}"
    state: directory
    mode: u=rwx,g=,o=

- import_tasks: ../../common/tasks/create-sslkeypair.yml
  vars:
    priv_key_file: "{{ internal_cert_priv_key_file }}"
    pub_key_file: "{{ internal_cert_pub_key_file }}"

- import_tasks: ../../common/tasks/create-cert-request.yml
  vars:
    priv_key_file: "{{ internal_cert_priv_key_file }}"
    csr_file: "{{ internal_cert_csr }}"
    csr_config: "{{ internal_cert_config }}"

- import_tasks: ../../common/tasks/create-cert.yml
  vars:
    priv_key_file: "{{ internal_cert_priv_key_file }}"
    csr_file: "{{ internal_cert_csr }}"
    cert_file: "{{ internal_cert_cert }}"
    days: "{{ internal_cert_days }}"
    ca_cert_file: "{{ internal_ca_cert }}"
    ca_cert_priv_key_file: "{{ internal_ca_priv_key_file }}"

- name: Store keys in variables  
  set_fact:
    vault_int_cert_priv: "{{ lookup('file',  '{{ internal_cert_priv_key_file }}') }}"
    vault_int_cert_pub: "{{ lookup('file',  '{{ internal_cert_pub_key_file }}') }}"
    vault_int_cert: "{{ lookup('file',  '{{ internal_cert_cert }}') }}"
