---

- name: Copy public key of current user to ~/.ssh/authorized_keys of user.
  
  # sudo to ansible user to copy public key into authorized_keys
  become: yes
  become_user: "{{ user_to_create }}"

  vars:
    ansible_become_pass: "{{ ssh_pass }}"

  authorized_key:
    user: "{{ user_to_create }}"
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"