
- name: Create a volume group on top of /dev/sda1 with physical extent size = 32MB
  lvg:
    vg: ubuntu-vg
    pvs: /dev/sda3
    pesize: 9G

- name: Create a logical volume of 512m
  lvol:
    vg: ubuntu-vg
    lv: mariadb
    size: 1G
  register: lvdata

- name: info
  debug:
    msg: "{{ lvdata }}"

- name: Create mount directory
  file:
    path: /mnt/mariadb
    state: directory
    mode: u=rwx,g=,o=

- name: Format volume
  filesystem:
    fstype: xfs
    dev: "/dev/{{ lvdata.vg }}/{{ lvdata.lv }}"


- name: Mount mariadb
  mount:
    path: /mnt/mariadb
    src: /dev/ubuntu-vg/mariadb
    fstype: xfs
    opts: defaults
    state: mounted
