---

- name: install python on remote host
  raw: 'sudo apt-get -y install python3'

- name: install setuptools
  apt:
    name: python-setuptools
    state: latest 
    update_cache: yes 

- name: install pip
  apt:
    name: python-pip
    state: latest 
    update_cache: yes 
