---

# OpenLDAP image settings
nginx_docker_image: blabla
nginx_docker_image_tag: alpine

# OpenLDAP container settings
nginx_docker_container_name: nginx
nginx_docker_container_hostname: nginx-server
nginx_docker_container_exposes_ports: ["80", "443"]
nginx_docker_container_publish_ports: ["80:80", "443:443"]
nginx_max_memory: null

# OpenLDAP data volume settings
nginx_data_volume_name: nginx-site-data
nginx_config_volume_name: openldap-config
nginx_site_data_volume_container_mount_point: /var/lib/ldap
nginx_config_volume_container_mount_point: /etc/ldap/slapd.d


# Deployment hints
recreate_nginx_container: "{{'yes' if recreate_nginx_container | lower is match('y|yes') else 'no'}}"
recreate_nginx_volumes: "{{'always' if recreate_nginx_volumes | lower is match('y|yes') else 'never'}}"