---

# ssh vault location
ssh_vault_location: "{{ inventory_dir}}/group_vars/local/vault-ssh.yml"
ssh_vault_id: "{{ current_inventory_env }}-ssh"

# file for key pair generation
keypair_file: "ssh-key"

# secrets vault location
secrets_vault_location: "{{ inventory_dir}}/group_vars/all_servers/vault-secrets.yml"
secrets_vault_id: "{{ current_inventory_env }}-secrets"

# password for the ansible user (used for sudo lateron).
deployment_user_pass: "{{ lookup('password', '/tmp/passwordfile chars=ascii_letters length=20') }}"