---

- name: Create vault yaml with keys
  template:
    src: templates/ssh-vault-template.yml
    dest: "{{ ssh_vault_location }}"
    owner: "{{ current_user }}"
    mode: u=rw,g=,o=

- name: Encrypt vault.yml containing the keypairs for the ansible user
  shell: ansible-vault encrypt "{{ ssh_vault_location }}" --vault-id "{{ ssh_vault_id }}@prompt"
  

  
