---

- name: Check presence of files ssh-vault
  stat:
    path: "{{ ssh_vault_location }}"
  register: ssh_vault_stat

- name: File exists?
  debug: 
    msg: "{{ ssh_vault_location }} already exists, this one will be used."
  when: ssh_vault_stat.stat.exists == true

- name: "Create {{ ssh_vault_location | basename }} with ssh keys"
  template:
    src: templates/ssh-vault-template.j2
    dest: "{{ ssh_vault_location }}"
    owner: "{{ current_user }}"
    mode: u=rw,g=,o=
  when: ssh_vault_stat.stat.exists == false or
        recreate_vaults_input == 'y'

- name: "Encrypt {{ ssh_vault_location | basename }} containing the keypairs for the ansible user"
  shell: ansible-vault encrypt "{{ ssh_vault_location }}" --vault-id "{{ ssh_vault_id }}@prompt"
  when: ssh_vault_stat.stat.exists == false or
        recreate_vaults_input == 'y'
  

  
