---

- name: Create directory for keypair
  file:
    path: "{{ keypair_location }}"
    state: directory
    mode: u=rwx,g=,o=

- name: Generate SSH keypair for accessing the targets
  openssh_keypair:
    type: rsa
    state: present
    size: 4096
    comment: "key-{{ current_user }}"
    path: "{{ keypair_location }}/{{ keypair_file }}"
    owner: "{{ current_user }}"
    mode: u=rw,g=,o=

- name: Store keys in variables  
  set_fact:
    vault_ssh_priv: "{{ lookup('file',  '{{ keypair_location }}/{{keypair_file}}') }}"
    vault_ssh_pub: "{{ lookup('file',  '{{ keypair_location }}/{{keypair_file}}.pub') }}"

- name: remove priv keypair from disk
  file:
    state: absent
    path: "{{ keypair_location }}/{{ keypair_file }}"

- name: remove priv keypair from disk
  file:
    state: absent
    path: "{{ keypair_location }}/{{ keypair_file }}.pub"
