---

# Generate keypair and store it in facts / vars: vault_ssh_priv, vault_ssh_pub
# Vars needed: 
# - current_user: user running this script
# - keypair_location: where is the keypair generated
# - keypair_file: filename of the private key
- import_tasks: generate-ssh-keypair.yml  

# Create a vault in with the ssh keys generated above
# Vars needed: 
# - ssh_vault_location : where do we need to put the vault
# - vault_id: id of the vault, for password identification
# - vault_ssh_priv
# - vault_ssh_pub
- import_tasks: create-ssh-vault.yml  
  