---

all:
  children:
    local:
      hosts: 
        127.0.0.1:
    web_servers:
      hosts:
        nnserver-1:
        nnserver-2:
    db_servers:
      hosts:
        nnserver-2:
    ldap_servers:
      hosts:
        nnserver-2:
    nas_servers:
      hosts:
        nnserver-3:
    all_servers:
      children:
        web_servers:
        db_servers:
        ldap_servers:
        nas_servers:
    # servers exposed to 'the external network'
    exposed_servers:
      children:
        web_servers:
    # servers only reachable from the internal network
    internal_servers:
      children:
        db_servers:
        ldap_servers:
        nas_servers:

