---

all:
  children:
    local:
      hosts: 
        127.0.0.1:
    webservers:
      children:
        webserver1:
          hosts:
            10.0.0.3:
        webserver2:
          hosts:
            10.0.0.4:
    all_servers:
      children:
        webservers:
