---

all:
  children:
    local:
      hosts: 
        127.0.0.1:
    web_servers:
      hosts:
        10.0.0.3:
        10.0.0.4:
    db_servers:
      hosts:
        10.0.0.4:
    ldap_servers:
      hosts:
        10.0.0.4:
    all_servers:
      children:
        web_servers:
        db_servers:
        ldap_servers:
    # servers exposed to 'the external network'
    exposed_servers:
      children:
        web_servers:
    # servers only reachable from the internal network
    internal_servers:
      children:
        db_servers:
        ldapserver:

