vault_deployment_user_pass: "{{ deployment_user_pass | default('') }}"
vault_openldap_admin_password: "{{ openldap_admin_password | default('') }}"
vault_postgresql_postgres_password: "{{ postgresql_postgres_password | default('') }}"
