---

- name: Create directory for keypair
  file:
    path: "{{ ssh_keypair_location }}"
    state: directory
    mode: u=rwx,g=,o=

- name: Create pub key
  template:
    src: templates/pub-key-template.j2
    dest: "{{ ssh_key_file_from_vault }}.pub"
    owner: "{{ current_user }}"
    mode: u=rw,g=,o=
