---

- name: Create directory for keypair
  file:
    path: "{{ keypair_location }}"
    state: directory
    mode: u=rwx,g=,o=

- name: Create priv key
  template:
    src: templates/priv-key-template.j2
    dest: "{{ ssh_key_file_from_vault }}.priv"
    owner: "{{ current_user }}"
    lstrip_blocks: true
    trim_blocks: false
    mode: u=rw,g=,o=
