---

# current inventory 
current_inventory_env: "{{ inventory_dir | basename }}"

# resource directory
resource_dir: "{{ inventory_dir }}/../../resources/{{ current_inventory_env }}"

# CA / certificates to copy to host (if needed)
cacerts_dir:  "{{ resource_dir }}/cacerts"
certs_dir:  "{{ resource_dir }}/certs"
ca_certs: "{{ query('fileglob', cacerts_dir + '/*.crt') }}"
internal_cacerts_ca_file: "internal-ca.crt"
internal_certs_cert_file: "internal-cert.crt"

# Current user is used for initial ssh connection.
current_user: "{{ lookup('env','USER') }}"
current_user_home: "{{ lookup('env','HOME') }}"

# User on the target that will be used for ansible deployments.
deployment_user: ansible
# Groups of the deployment user.
deployment_user_groups: sudo

# Current user is used for initial ssh connection.
ssh_user: "{{ current_user }}"

# keypair settings (key will only be here during setup of authentication for host)
ssh_keypair_location: "{{ current_user_home }}/ansible/keypairs/{{ current_inventory_env }}"

# ca keypair and certificates
ca_stuff_location: "{{ current_user_home }}/ansible/certs/{{ current_inventory_env }}/ca-stuff"

# ca keypair and certificates
certs_stuff_location: "{{ current_user_home }}/ansible/certs/{{ current_inventory_env }}/certs-stuff"

# private key location for key authentication ()
ssh_key_file_from_vault: "{{ ssh_keypair_location }}/ssh-key-from-vault"

