---

# Create ssh key pair and put it in a vault.
- hosts: 
    - local

  # do not use ssh to connect to local host
  connection: local

  vars:
  
  roles:
    - create-secrets-vault
    - create-ssh-vault
