---

# Create ssh key pair and put it in a vault.
- hosts: 
    - local

  # do not use ssh to connect to local host
  connection: local

  vars:
    internal_ca_key_file: "{{ ca_stuff_location }}/{{ current_inventory_env }}-int-ca-key"
    internal_ca_cert: "{{ ca_stuff_location }}/{{ current_inventory_env }}-int-ca-cert.crt"
    internal_ca_csr: "{{ ca_stuff_location }}/{{ current_inventory_env }}-int-ca-cert.csr"
    internal_cert_key_file: "{{ certs_stuff_location }}/{{ current_inventory_env }}-int-cert-key"
    internal_cert_cert: "{{ certs_stuff_location }}/{{ current_inventory_env }}-int-cert.crt"
    internal_cert_csr: "{{ certs_stuff_location }}/{{ current_inventory_env }}-int-cert.csr"
  
  roles:
    #- create-secrets-vault
    #- create-ssh-vault
    - create-certs-vault
