---
  # Prepare the authentication to the targets.
  # Needs besides the ssh  package the sshpass package 
  # Ubuntu / Debian: sudo apt install sshpass or 
  # OSX: brew create https://sourceforge.net/projects/sshpass/files/sshpass/1.06/sshpass-1.06.tar.gz --force
  #      brew install sshpass
 
- hosts: webserver1

  vars:
    # current user is used for initial ssh connection
    ssh_user: "{{ lookup('env','USER') }}"

  vars_prompt: 
    - name: ssh_pass
      prompt: "Password for user [{{ssh_user}}] to connect to target (using ssh)?"
      private: yes

  roles:
    - prepare-targets