---

# Write ssh keys to disk for ssh key authentication
# 
- hosts: 
    - local

  # do not use ssh to connect to local host
  connection: local

  vars:
  
  roles:
    - local-setup-host-key
    - local-install-packages

    