---

- hosts: 
  - webservers

  vars:
    # sudo to ansible user to copy public key into authorized_keys
    ansible_become: yes
    ansible_become_pass: "{{ deployment_user_pass }}"

    # ssh username / sudo password
    ansible_user: "{{ deployment_user }}"
    ansible_ssh_private_key_file: "{{ ssh_key_file_from_vault }}.priv"
    
  roles:
    - mariadb-docker
