---

- hosts:
  - webservers
    
  become: yes
  become_user: root

  vars:
    # ssh username / password
    ansible_user: "{{ deployment_user }}"
    ansible_ssh_private_key_file: "{{ ssh_key_file_from_vault }}.priv"
    
    ansible_become_pass: "{{ deployment_user_pass }}"
    
  roles:
    - host-install-base
