---

- hosts:
  - webservers
    
  become: yes
  become_user: root

  vars:
    # ssh username / password
    ansible_user: "{{ deployment_user }}"
    ansible_ssh_key_file: "{{ priv_key_from_vault_file }}"
    ansible_become_pass: "{{ sudo_pass }}"
    
  roles:
    - host-install-base
