---

# warnCreate ssh key pair
- hosts: 
    - local

  # do not use ssh to connect to local host
  connection: local

  vars:
  
  roles:
    - generate-ssh-keypair


# Create ssh key pair
- hosts: 
    - local

  # do not use ssh to connect to local host
  connection: local

  vars:
  
  roles:
    - generate-ssh-keypair

# Prepare target for ansible authentication:
# - Create ansible user on target.
# - Copy executing user's public key to authorized_keys of ansible user
# After this the executing user is able to log in as ansible user using ssh key authentication 
- hosts: 
  - webservers

  vars_prompt: 
    - name: ssh_pass 
      prompt: |-
              User [{{ lookup('env', 'USER') }}] will be used to connect to the targets for creating an ansible user.
              After that, a newly generated the public ssh key will be copied to the authorized_keys of the ansible user.
              Please provide the password for user [{{ lookup('env', 'USER') }}]
      private: yes

  vars:
    # ssh username / password
    ansible_user: "{{ ssh_user }}"
    ansible_ssh_pass: "{{ ssh_pass }}"

  roles:
    - host-user-pubkey

# create vault
- hosts: 
    - local

  # do not use ssh to connect to local host
  connection: local

  vars:
  
  roles:
    - generate-vault
    