---

- hosts: 
  - internal_servers

  vars_prompt:
    - name: recreate_nginx_container_input
      prompt: |-
              Should the NginX container be recreated if it is already there (y/n)?
      private: false
      unsafe: true
      default: "n"

    - name: recreate_nginx_volumes_input
      prompt: |-
              Recreate NginX volumes (you will loose persistent config / data / logging, and container will be recreated!)?
      private: false
      unsafe: true
      confirm: yes
      default: "n"

  vars:
    # sudo to ansible user to copy public key into authorized_keys
    ansible_become: true
    ansible_become_pass: "{{ deployment_user_pass }}"
    config_resources: "{{ resource_dir }}/nginx-internal"

    # ssh username / sudo password
    ansible_user: "{{ deployment_user }}"
    ansible_ssh_private_key_file: "{{ ssh_key_file_from_vault }}.priv"

  roles:
    - nginx
