---

- hosts:
  - webservers
    
  become: yes
  become_user: root

  vars_prompt: 
    - name: ssh_pass 
      prompt: |-
              Please provide the password for user [{{ lookup('env', 'USER') }}]
      private: yes
      when: ssh_pass is undefined

  vars:
    # ssh username / password
    ansible_user: "{{ ssh_user }}"
    ansible_ssh_pass: "{{ ssh_pass }}"
    ansible_become_pass: "{{ ssh_pass }}"
    
  roles:
    - host-install-packages
