---

- hosts: 
  - ldap_servers

  vars_prompt:
    - name: recreate_openldap_container_input
      prompt: |-
              Should the OpenLDAP container be recreated if it is already there (y/n)?
      private: false
      unsafe: true
      #default: "n"
      default: "y"

    - name: recreate_openldap_volumes_input
      prompt: |-
              Recreate OpenLDAP volumes (you will loose persistent data, and container will be recreated!)?
      private: false
      unsafe: true
      confirm: yes
      #default: "n"
      default: "y"

    - name: openldap_domain_input
      prompt: |-
              Please give the domain name for the OpenLDAP server
      private: false
      unsafe: false
      default: example.com

    - name: openldap_organization_name_input
      prompt: |-
              Please give the OpenLDAP organization name
      private: false
      unsafe: true
      confirm: false
      default: Example Corp      

    - name: openldap_admin_pass_input
      prompt: |-
              Password for the OpenLDAP administrator
      private: true
      unsafe: true
      confirm: yes
      default: "admin"

  vars:
    # sudo to ansible user
    ansible_become: true
    ansible_become_pass: "{{ deployment_user_pass }}"

    # ssh username / sudo password
    ansible_user: "{{ deployment_user }}"
    ansible_ssh_private_key_file: "{{ ssh_key_file_from_vault }}.priv"

    # force recreation of the secrets vault (with the open-ldap admin password)
    recreate_vaults_input: "y"

  roles:
    # install openldap
    - openldap
    # update the secrets vault with the admin password 
    - create-secrets-vault

