---

# Shutdown docker
- name: Stop docker service
  systemd:
    name: docker
    state: stopped

#######################################
# Docker volumes on lvm logical volume
#######################################

- name: "Create mount directory for docker volumes on {{ docker.data.mount_dir }}"
  file:
    path: "{{ docker.data.mount_dir }}"
    state: directory
    mode: u=rwx,g=,o=

- name: Format volume for docker storage
  filesystem:
    fstype: xfs
    opts: -n ftype=1
    dev: "/dev/{{ docker.data.volume_group }}/{{ docker.data.logical_volume }}"

- name: "Mount {{ docker.data.mount_dir }} to /dev/{{ docker.data.volume_group }}/{{ docker.data.logical_volume }}"
  mount:
    path: "{{ docker.data.mount_dir }}"
    src: "/dev/{{ docker.data.volume_group }}/{{ docker.data.logical_volume }}"
    fstype: xfs
    opts: defaults
    state: mounted

#- name: "file stat for {{ docker.docker_dir }}/volumes"
#  stat: 
#    path: "{{ docker.docker_dir }}/volumes"
#  register: docker_volumes_stat

#- name: If docker volumes dir is not a symlink, or not to the lvm volume, copy the data to the lvm volume
#  copy:
#   src: "{{ docker.docker_dir }}/volumes/"
#    dest: "{{ docker.data.mount_dir }}/"
#    remote_src: true
#    mode: preserve
#  when: (not docker_volumes_stat.stat.islnk) or 
#        (not (docker_volumes_stat.stat.lnk_target == ((docker.data.mount_dir + "/") | dirname)))

#- name: "Remove {{ docker.docker_dir }}/volumes"
#  file:
#    path: "{{ docker.docker_dir }}/volumes"
#    state: absent

# Create symbolic link 
#- name: "Create symbolic link from {{ docker.docker_dir }}/volumes to {{ docker.data.mount_dir }}"
#  file:
#    src: "{{ docker.data.mount_dir }}"
#    dest: "{{ docker.docker_dir }}/volumes"
#    owner: root
#    group: root
#    state: link
#    mode: u=rwx,g=x,o=x

################################

- name: Startup docker again with lvm data volume
  systemd:
    name: docker
    state: started

