---

# Shutdown docker
- name: Stop docker service
  systemd:
    name: docker
    state: stopped

#######################################
# Docker volumes on lvm logical volume
#######################################

# Create mount point for docker storage lv
- name: Create mount directory for docker storage
  file:
    path: "{{ docker.data.mount_dir }}"
    state: directory
    mode: u=rwx,g=,o=

# Format logical volume
- name: Format volume for docker storage
  filesystem:
    fstype: xfs
    opts: -n ftype=1
    dev: "/dev/{{ docker.data.volume_group }}/{{ docker.data.logical_volume }}"

# Mount logical volume
- name: "Mount {{ docker.data.mount_dir }}"
  mount:
    path: "{{ docker.data.mount_dir }}"
    src: "/dev/{{ docker.data.volume_group }}/{{ docker.data.logical_volume }}"
    fstype: xfs
    opts: defaults
    state: mounted

# Move /var/lib/docker to /var/lob/docker.prev
- name: stat /var/lib/docker/volumes
  stat: 
    path: /var/lib/docker/volumes
  register: var_lib_docker_volumes_stat

- name: Move /var/lib/docker/volumes to /var/lib/docker/volumes.prev
  command: mv /var/lib/docker/volumes /var/lib/docker/volumes.prev
  when: var_lib_docker_volumes_stat.stat.exists

# symbolic link var_lib_docker_stat
- name: "Create symbolic link from /var/lib/docker/volumes to {{ docker.data.mount_dir }}"
  file:
    src: "{{ docker.data.mount_dir }}"
    dest: /var/lib/docker/volumes
    owner: root
    group: root
    state: link
    mode: u=rwx,g=x,o=x

################################

- name: Startup docker again with storage driver set to overlay2
  systemd:
    name: docker
    state: started

