---

# Shutdown docker
- name: Stop docker service
  systemd:
    name: docker
    state: stopped

################################
# Docker storage on lvm
################################

#- name: "Create mount directory for docker storage lv ({{ docker.storage.mount_dir }})"
#  file:
#    path: "{{ docker.storage.mount_dir }}"
#    state: directory
#    mode: u=rwx,g=,o=

- name: "Format logical volume (/dev/{{ docker.storage.volume_group }}/{{ docker.storage.logical_volume }}) for docker storage"
  filesystem:
    fstype: xfs
    opts: -n ftype=1
    dev: "/dev/{{ docker.storage.volume_group }}/{{ docker.storage.logical_volume }}"

- name: "Mount {{ docker.storage.mount_dir }}"
  mount:
    path: "{{ docker.storage.mount_dir }}"
    src: "/dev/{{ docker.storage.volume_group }}/{{ docker.storage.logical_volume }}"
    fstype: xfs
    opts: defaults
    state: mounted

#- name: "Create symbolic link from {{ docker.docker_dir }} to {{ docker.storage.mount_dir }}"
#  file:
#    src: "{{ docker.storage.mount_dir }}"
#    dest: /var/lib/docker
#    owner: root
#    group: root
#    state: link
#    mode: u=rwx,g=x,o=x

################################
# Configure docker for overlay2
################################

- name: create /etc/docker/daemon.json if it is not there yet
  file:
    path: /etc/docker/daemon.json
    state: touch
    mode: u=rwx,g=,o=

- name: Fetch daemon.json from remote system
  slurp:
    src: /etc/docker/daemon.json
  register: daemon_json

- name: Add overlay2 storage-driver setting to docker's daemon.json
  set_fact:
    # Convert file content or {} (when empty) from json to dictionary
    daemon_json_content: "{{ (\"{ }\" if daemon_json.content | trim  == \"\" else daemon_json.content | b64decode) | from_json | combine({ 'storage-driver': 'overlay2' }) }}"

- name: Write modified daemon.json back
  copy: 
    content: "{{ daemon_json_content | default([]) | to_nice_json(indent=2) }}" 
    dest: /etc/docker/daemon.json

################################

- name: Startup docker again with storage driver set to overlay2
  systemd:
    name: docker
    state: started

