---

- name: Install prerequisites
  apt:
    name: ['apt-transport-https', 'curl', 'software-properties-common']
    update_cache: no

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable

- name: Install docker-ce
  apt: 
    update_cache: no
    name: docker-ce
    state: latest

- name: Install docker-compose
  apt: 
    update_cache: no
    name: docker-ce
    state: latest

############################################
# configure docker proxy settings if needed
############################################

- name: configure docker proxy settings
  block:
  - name:  
    file:
      path: /etc/systemd/system/docker.service.d
      state: directory
      mode: u=rwx,g=rx,o=rx

  - name: set proxies for docker
    file: 
      path: /etc/systemd/system/docker.service.d/http-proxy.conf
      state: touch
      mode: u=rw,g=r,o=r

  when: proxy_settings is defined


