---

- name: Install prerequisites
  apt:
    name: ['apt-transport-https', 'curl', 'software-properties-common']
    update_cache: no

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable

- name: Install docker-ce
  apt: 
    update_cache: no
    name: docker-ce
    state: latest

- name: Install docker-compose
  apt: 
    update_cache: no
    name: docker-ce
    state: latest

############################################
# configure docker proxy settings if needed
############################################

- name: configure docker proxy settings
  block:
  - name:  
    file:
      path: "{{ docker_conf | dirname }}"
      state: directory
      group: root
      mode: u=rwx,g=rx,o=rx

  - name: modify docker config file {{ docker_conf }}
    template:
      src: "templates/{{ docker_conf | basename }}.j2"
      dest: "{{ docker_conf }}"
      group: root
      mode: u=rw,g=r,o=r

  - name: daemon_reload fr changed settings and restart docker
    systemd:
      state: restarted
      daemon_reload: yes
      name: docker

  when: proxy_settings is defined


