---

# User to create on the target that will be used for ansible deployments.
deployment_user: ansible
# Groups to add the new user to.
deployment_user_groups: sudo

# CA certificates to copy to host (if needed)
ca_certs_dir:  "{{ inventory_dir }}/../../resources/{{ current_inventory_env }}/certs"
ca_certs: "{{ query('fileglob', ca_certs_dir + '/*.crt') }}"

# SSH service name
ssh_service: sshd

# LVM related vars
lvm:
  volume_groups: 
    ubuntu:
      name: ubuntu-vg
      physical_volumes: ["/dev/sda3"]
      size: 5G
      volumes:
        ubuntu_main:
          name: ubuntu-lv
          size: 4G

    docker:
      name: docker-vg
      physical_volumes: ["/dev/sdb"]
      size: 2G
      volumes:
        ubuntu_storage:
          name: docker-storage-lv
          size: 100%FREE

    #docker_data:
    #  name: docker-data-vg
    #  physical_volumes: ["/dev/sdc"]
    #  size: 2G
      # volumes:
      #   volumes will be created by the playbooks for the different containers
    

# docker hints
docker:
  storage:
    # 
    volume: "{{ lvm.volume_groups['docker'].volumes[0].name }}"
    mount_dir:   
  data:
    volume_group: "{{ lvm.volume_groups['docker_data'].name }}"
