---

- name: Create vault yaml with keys and password
  template:
    src: templates/vault-template.yml
    dest: "{{ vault_location }}"
    owner: "{{ current_user }}"
    mode: u=rw,g=,o=

- name: Encrypt vault.yml containing the keypairs for the ansible user
  shell: ansible-vault encrypt "{{ vault_location }}" --vault-id "{{ vault_id }}@prompt"
  

- name: remove keypair
  file:
    state: absent
    path: "{{ keypair_location }}"
  
